export enum PermissionEnum {
    // VIEW Permissions
    VIEW_TRANSACTIONS = 'VIEW_TRANSACTIONS',
    VIEW_WALLET = 'VIEW_WALLET',
    VIEW_REPORTS = 'VIEW_REPORTS',
    VIEW_USERS = 'VIEW_USERS',
    VIEW_AUDIT_LOG = 'VIEW_AUDIT_LOG',

    // CREATE Permissions
    CREATE_TRANSACTION = 'CREATE_TRANSACTION',
    CREATE_HIGH_VALUE_TRANSACTION = 'CREATE_HIGH_VALUE_TRANSACTION',
    CREATE_VERY_HIGH_VALUE_TRANSACTION = 'CREATE_VERY_HIGH_VALUE_TRANSACTION',
    CREATE_USER = 'CREATE_USER',

    // UPDATE Permissions
    UPDATE_TRANSACTION = 'UPDATE_TRANSACTION',
    UPDATE_WALLET = 'UPDATE_WALLET',
    UPDATE_USER = 'UPDATE_USER',

    // DELETE Permissions
    DELETE_TRANSACTION = 'DELETE_TRANSACTION',
    CANCEL_TRANSACTION = 'CANCEL_TRANSACTION',

    // MANAGE Permissions
    MANAGE_USERS = 'MANAGE_USERS',
    MANAGE_ROLES = 'MANAGE_ROLES',
    MANAGE_PERMISSIONS = 'MANAGE_PERMISSIONS',
    MANAGE_TENANT = 'MANAGE_TENANT',
    MANAGE_PRODUCTS = 'MANAGE_PRODUCTS',

    // ADMIN Permissions
    ADMIN_FULL_ACCESS = 'ADMIN_FULL_ACCESS',
    ADMIN_VIEW_SENSITIVE_DATA = 'ADMIN_VIEW_SENSITIVE_DATA',
    ADMIN_FORCE_TRANSACTION = 'ADMIN_FORCE_TRANSACTION',
}